version: '3.7'

services:
  ssh:
    image: ssh
    build:
      context: .
      dockerfile: ssh/Dockerfile
      target: development
    volumes:
      - ./ssh:/go/src/github.com/shellhub-io/shellhub/ssh
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
    networks:
      - shellhub
    environment:
      - SHELLHUB_HOSTED=${SHELLHUB_HOSTED}
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
    volumes:
      - ./api:/go/src/github.com/shellhub-io/shellhub/api
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shellhub
  ui:
    image: ui
    build:
      context: .
      dockerfile: ui/Dockerfile
      target: development
    volumes:
      - ./ui:/src
    networks:
      - shellhub
    environment:
      - SHELLHUB_HOSTED=${SHELLHUB_HOSTED}
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - SHELLHUB_VERSION=latest
      - SHELLHUB_HOSTED=${SHELLHUB_HOSTED}
    networks:
      - shellhub
  agent:
    image: agent
    restart: on-failure
    build:
      context: .
      dockerfile: agent/Dockerfile
      target: development
      args:
        SHELLHUB_VERSION: latest
    privileged: true
    network_mode: host
    pid: host
    environment:
      - SHELLHUB_SERVER_ADDRESS=http://172.17.0.1
      - SHELLHUB_PRIVATE_KEY=/go/src/github.com/shellhub-io/shellhub/agent/shellhub.key
      - SHELLHUB_TENANT_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - SHELLHUB_VERSION=${SHELLHUB_VERSION}
    volumes:
      - ./agent:/go/src/github.com/shellhub-io/shellhub/agent
      - ./pkg:/go/src/github.com/shellhub-io/shellhub/pkg
      - /:/host
      - /dev:/dev
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api
      - ssh
      - gateway
  mongo:
    networks:
      - shellhub
  autossl:
    image: tianon/true
    networks:
      - shellhub

networks:
  shellhub:
    name: shellhub_network
